// app/layout.tsx
import ClientLayout from './ClientLayout';

export const metadata = {
  title: 'Home',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}